"""empty message

Revision ID: 00cea04f0451
Revises: 
Create Date: 2024-12-30 14:38:38.760605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cea04f0451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.drop_constraint('catalog_ingramPartNumber_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.create_unique_constraint('catalog_ingramPartNumber_key', ['ingramPartNumber'])

    # ### end Alembic commands ###
